spring.application.name=bff-movil
server.address=127.0.0.1
server.port=8082
server.compression.enabled=true
server.compression.min-response-size=256B
server.error.include-message=never
server.error.include-stacktrace=never
spring.jackson.deserialization.fail-on-unknown-properties=true
bank.channel=mobile
bank.web-identities=${BANK_WEB_IDENTITIES}
bank.mobile-identities=${BANK_MOBILE_IDENTITIES}
bank.atm-identities=${BANK_ATM_IDENTITIES}
bank.core-url=${BANK_CORE_URL:http://127.0.0.1:8080}
bank.reports-url=${BANK_REPORTS_URL:http://127.0.0.1:8084}
