spring.application.name=servicio-reportes
server.address=127.0.0.1
server.port=8084
server.error.include-message=never
server.error.include-stacktrace=never
bank.channel=reports
bank.web-identities=${BANK_WEB_IDENTITIES}
bank.mobile-identities=${BANK_MOBILE_IDENTITIES}
bank.atm-identities=${BANK_ATM_IDENTITIES}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bankdb}
spring.datasource.username=${DB_USERNAME:bankuser}
spring.datasource.password=${DB_PASSWORD:bankpassword}
spring.sql.init.mode=never
