spring.application.name=servicio-bancario
server.address=127.0.0.1
server.port=8080
server.error.include-message=never
server.error.include-stacktrace=never
spring.jackson.deserialization.fail-on-unknown-properties=true
bank.channel=core
bank.web-identities=${BANK_WEB_IDENTITIES}
bank.mobile-identities=${BANK_MOBILE_IDENTITIES}
bank.atm-identities=${BANK_ATM_IDENTITIES}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bankdb}
spring.datasource.username=${DB_USERNAME:bankuser}
spring.datasource.password=${DB_PASSWORD:bankpassword}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-core.sql
