spring.application.name=bff-cajero
server.address=127.0.0.1
server.port=8083
server.compression.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
spring.jackson.deserialization.fail-on-unknown-properties=true
bank.channel=atm
bank.web-identities=${BANK_WEB_IDENTITIES}
bank.mobile-identities=${BANK_MOBILE_IDENTITIES}
bank.atm-identities=${BANK_ATM_IDENTITIES}
bank.core-url=${BANK_CORE_URL:http://127.0.0.1:8080}
